server:
  port: 9090

spring:
  application:
    name: demo-backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 100MB
      file-size-threshold: 0
#      location: public/temp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

upload:
  path: public/videos
